# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: "postgres:13"
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"